Repository Team-return/JOBIS-ANDROID-V2, pull requests merged in 2024-03, with the labels that each got.

#94 🔗 :: (#41) 모집의뢰서 리스트 비즈니스 로직 작성
  core/common/src/main/java/team/retum/common/enums/CodeType.kt
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/code/CodeRepository.kt
  core/data/src/main/java/team/retum/data/repository/code/CodeRepositoryImpl.kt
  core/data/src/main/java/team/retum/data/repository/recruitment/RecruitmentRepository.kt
  core/data/src/main/java/team/retum/data/repository/recruitment/RecruitmentRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/CodesEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/CompanyCountEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/RecruitmentCountEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/RecruitmentsEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/code/FetchCodeUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/recruitment/FetchRecruitmentCountUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/recruitment/FetchRecruitmentsUseCase.kt
  core/network/src/main/java/team/retum/network/api/CodeApi.kt
  core/network/src/main/java/team/retum/network/api/RecruitmentApi.kt
  core/network/src/main/java/team/retum/network/datasource/code/RemoteCodeDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/code/RemoteCodeDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/datasource/recruitment/RemoteRecruitmentDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/recruitment/RemoteRecruitmentDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/team/retum/network/model/response/FetchCodesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchRecruitmentPageCountResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchRecruitmentsResponse.kt
  feature/recruitment/build.gradle.kts
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentFilterScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/SearchRecruitmentScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentContent.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentFilterViewModel.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/SearchRecruitmentViewModel.kt
  feature/recruitment/src/main/res/drawable/ic_empty_company.png
  feature/recruitment/src/main/res/values/strings.xml
Labels: 기능 구현

#92 🔗 :: (#91) 홈 화면 기능 구현
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/common/src/main/java/team/retum/common/enums/AttachmentType.kt
  core/common/src/main/java/team/retum/common/enums/BannerType.kt
  core/common/src/main/java/team/retum/common/enums/Department.kt
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepository.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepositoryImpl.kt
  core/data/src/main/java/team/retum/data/repository/banner/BannerRepository.kt
  core/data/src/main/java/team/retum/data/repository/banner/BannerRepositoryImpl.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepository.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/application/AppliedCompaniesEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/application/EmploymentCountEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/application/RejectionReasonEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/banner/BannersEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/student/StudentInformationEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/application/FetchAppliedCompaniesUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/application/FetchEmploymentCountUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/application/FetchRejectionReasonUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/banner/FetchBannersUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/student/FetchStudentInformationUseCase.kt
  core/network/src/main/java/team/retum/network/api/ApplicationApi.kt
  core/network/src/main/java/team/retum/network/api/BannerApi.kt
  core/network/src/main/java/team/retum/network/api/StudentApi.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/datasource/banner/RemoteBannerDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/banner/RemoteBannerDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/team/retum/network/di/RequestUrls.kt
  core/network/src/main/java/team/retum/network/model/response/FetchStudentInformationResponse.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchAppliedCompaniesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchEmploymentCountResponse.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchRejectionReasonResponse.kt
  core/network/src/main/java/team/retum/network/model/response/banner/FetchBannersResponse.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
Labels: 기능 구현

#95 🔗 :: (#42) 마이페이지 기능 구현
  app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/res/values/strings.xml
  core/data/src/main/java/team/retum/data/repository/company/CompanyRepository.kt
  core/data/src/main/java/team/retum/data/repository/company/CompanyRepositoryImpl.kt
  core/data/src/main/java/team/retum/data/repository/user/UserRepository.kt
  core/data/src/main/java/team/retum/data/repository/user/UserRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/company/ReviewableCompaniesEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/company/FetchReviewableCompaniesUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/user/SignOutUseCase.kt
  core/local/src/main/java/team/retum/jobis/local/datasource/user/LocalUserDataSource.kt
  core/local/src/main/java/team/retum/jobis/local/datasource/user/LocalUserDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/api/CompanyApi.kt
  core/network/src/main/java/team/retum/network/datasource/company/CompanyDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/company/CompanyDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/model/response/company/FetchReviewableCompaniesResponse.kt
  feature/landing/src/main/java/team/retum/landing/navigation/LandingNavigation.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/team/returm/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
  feature/mypage/src/main/java/team/returm/mypage/viewmodel/MyPageViewModel.kt
  feature/mypage/src/main/res/drawable/ic_user_profile.jpg
Labels: 기능 구현

#97 🔗 :: (#40) 회원가입 비즈니스 로직 작성
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  core/common/src/main/java/team/retum/common/enums/FileType.kt
  core/common/src/main/java/team/retum/common/utils/FileUtil.kt
  core/common/src/main/java/team/retum/common/utils/Regex.kt
  core/common/src/main/java/team/retum/common/utils/RequestType.kt
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/file/FileRepository.kt
  core/data/src/main/java/team/retum/data/repository/file/FileRepositoryImpl.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepository.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/file/PresignedUrlEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/file/CreatePresignedUrlUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/file/UploadFileUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/student/PostSignUpUseCase.kt
  core/network/src/main/java/team/retum/network/api/FileApi.kt
  core/network/src/main/java/team/retum/network/api/StudentApi.kt
  core/network/src/main/java/team/retum/network/datasource/file/RemoteFileDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/file/RemoteFileDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/team/retum/network/model/request/file/CreatePresignedUrlRequest.kt
  core/network/src/main/java/team/retum/network/model/request/student/PostSignUpRequest.kt
  core/network/src/main/java/team/retum/network/model/response/file/CreatePresignedUrlResponse.kt
  core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
  feature/signup/build.gradle.kts
  feature/signup/src/main/java/team/retum/signup/model/SignUpData.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SelectGenderNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SetPasswordNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SetProfileNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/TermsNavigation.kt
  feature/signup/src/main/java/team/retum/signup/ui/InputEmailScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/InputPersonalInfoScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SelectGenderScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetPasswordScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetProfileScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/TermsScreen.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/InputEmailViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/InputPersonalInfoViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/SelectGenderViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/SetPasswordViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/SetProfileViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/TermsViewModel.kt
  feature/signup/src/main/res/values/strings.xml
Labels: 기능 구현

#102 🔗 :: (#83) 리뷰 작성하기
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/review/ReviewRepository.kt
  core/data/src/main/java/team/retum/data/repository/review/ReviewRepositoryImpl.kt
  core/design-system/build.gradle.kts
  core/design-system/src/androidTest/java/team/retum/jobisdesignsystemv2/JobisTextTest.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/checkbox/CheckBox.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/textfield/JobisTextField.kt
  core/domain/src/main/java/team/retum/usecase/entity/FetchReviewDetailEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/FetchReviewsEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/PostReviewEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/review/FetchReviewDetailUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/review/FetchReviewsUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/review/PostReviewUseCase.kt
  core/network/src/main/java/team/retum/network/api/ReviewApi.kt
  core/network/src/main/java/team/retum/network/datasource/recruitment/RemoteRecruitmentDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/datasource/review/ReviewDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/review/ReviewDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/team/retum/network/model/request/PostReviewRequest.kt
  core/network/src/main/java/team/retum/network/model/response/FetchReviewDetailResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchReviewsResponse.kt
  feature/company/.gitignore
  feature/mypage/src/main/java/team/returm/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
  feature/review/.gitignore
  feature/review/build.gradle.kts
  feature/review/src/main/java/team/retum/review/navigation/PostReviewNavigation.kt
  feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
  feature/review/src/main/java/team/retum/review/viewmodel/ReviewViewModel.kt
  feature/review/src/main/res/drawable/ic_arrow_down.xml
  feature/review/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 기능 구현

#105 🔗 :: (104) 후기 재구현
  core/common/src/main/java/team/retum/common/component/Skills.kt
  core/common/src/main/java/team/retum/common/enums/ReviewProcess.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/checkbox/CheckBox.kt
  feature/mypage/src/main/java/team/returm/mypage/viewmodel/MyPageViewModel.kt
  feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
  feature/review/src/main/java/team/retum/review/viewmodel/ReviewViewModel.kt
  feature/review/src/main/res/values/strings.xml
Labels: 리팩토링

#98 🔗 :: (#93) 기업 상세 구현
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/data/src/main/java/team/retum/data/repository/company/CompanyRepository.kt
  core/data/src/main/java/team/retum/data/repository/company/CompanyRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/company/CompanyDetailsEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/company/FetchCompanyDetailsUseCase.kt
  core/network/src/main/java/team/retum/network/api/CompanyApi.kt
  core/network/src/main/java/team/retum/network/datasource/company/CompanyDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/company/CompanyDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/model/response/company/FetchCompanyDetailsResponse.kt
  feature/company/build.gradle.kts
  feature/company/src/main/java/team/retum/company/navigation/CompaniesNavigation.kt
  feature/company/src/main/java/team/retum/company/navigation/CompanyDetailsNavigation.kt
  feature/company/src/main/java/team/retum/company/navigation/SearchCompaniesNavigation.kt
  feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/ui/CompanyDetailsScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompanyDetailsViewModel.kt
  feature/company/src/main/res/values/strings.xml
Labels: 퍼블리싱

#107 🔗 :: (#99) 비밀번호 재설정 기능 구현
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  core/common/src/main/java/team/retum/common/enums/ResetPasswordNavigationArgumentType.kt
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepository.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/usecase/student/ChangePasswordUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/student/ComparePasswordUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/student/ResetPasswordUseCase.kt
  core/network/src/main/java/team/retum/network/api/StudentApi.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/RequestUrls.kt
  core/network/src/main/java/team/retum/network/model/request/student/ChangePasswordRequest.kt
  core/network/src/main/java/team/retum/network/model/request/student/ForgottenPasswordRequest.kt
  feature/change-password/build.gradle.kts
  feature/change-password/src/androidTest/java/team/retum/change_password/ExampleInstrumentedTest.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/navigation/ComparePasswordNavigation.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/navigation/ResetPasswordNavigation.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/ui/ComparePasswordScreen.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/ui/ResetPasswordScreen.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/viewmodel/ComparePasswordViewModel.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/viewmodel/ResetPasswordViewModel.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/navigation/ConfirmPasswordNavigation.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/navigation/ResetPasswordNavigation.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/ui/ConfirmPasswordScreen.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/ui/ResetPasswordScreen.kt
  feature/change-password/src/main/res/values/strings.xml
  feature/change-password/src/test/java/team/retum/change_password/ExampleUnitTest.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
  feature/verify-email/build.gradle.kts
  feature/verify-email/src/main/java/team/retum/jobis/verify/email/navigation/VerifyEmailNavigation.kt
  feature/verify-email/src/main/java/team/retum/jobis/verify/email/ui/VerifyEmailScreen.kt
  feature/verify-email/src/main/java/team/retum/jobis/verify/email/viewmodel/VerifyEmailViewModel.kt
  feature/verify-email/src/main/java/team/retum/jobis/verify_email/ui/VerifyEmailScreen.kt
  feature/verify-email/src/main/res/values/strings.xml
Labels: 기능 구현

#114 🔗 :: (#45) 지원하기 기능 구현
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/ApplicationNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/ApplicationScreen.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepository.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/usecase/application/ApplyCompanyUseCase.kt
  core/network/src/main/java/team/retum/network/api/ApplicationApi.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/model/request/application/ApplyCompanyRequest.kt
  feature/application/.gitignore
  feature/application/build.gradle.kts
  feature/application/src/main/java/team/retum/jobis/application/model/CompanyInfo.kt
  feature/application/src/main/java/team/retum/jobis/application/navigation/ApplicationNavigation.kt
  feature/application/src/main/java/team/retum/jobis/application/ui/ApplicationScreen.kt
  feature/application/src/main/java/team/retum/jobis/application/viewmodel/ApplicationViewModel.kt
  feature/application/src/main/res/values/strings.xml
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  settings.gradle.kts
Labels: 기능 구현

#113 🔗 :: (#112) 공지사항 리스트 기능 개발
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/notice/NoticeRepository.kt
  core/data/src/main/java/team/retum/data/repository/notice/NoticeRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/notice/NoticesEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/notice/FetchNoticesUseCase.kt
  core/network/src/main/java/team/retum/network/api/NoticeApi.kt
  core/network/src/main/java/team/retum/network/datasource/notice/NoticeDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/notice/NoticeDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/team/retum/network/di/RequestUrls.kt
  core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticesResponse.kt
  feature/notice/build.gradle.kts
  feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticesScreen.kt
  feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticesViewModel.kt
Labels: 기능 구현

#116 🔗 :: (#103) 홈 화면 체험형 현장실습 기능 구현
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/res/values/strings.xml
Labels: 기능 구현

#121 🔗 :: (#109) 모집의뢰서 필터
  core/common/src/main/java/team/retum/common/component/Skills.kt
  feature/interests/src/main/java/team/retum/jobis/interests/ui/InterestsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentFilterScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentFilterViewModel.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
  feature/recruitment/src/main/res/values/strings.xml
Labels: 기능 구현

#117 🔗 :: (#106) 면접후기 조회 구현
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  core/common/src/main/java/team/retum/common/component/ReviewContent.kt
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/domain/src/main/java/team/retum/usecase/entity/FetchReviewsEntity.kt
  feature/company/build.gradle.kts
  feature/company/src/main/java/team/retum/company/navigation/CompanyDetailsNavigation.kt
  feature/company/src/main/java/team/retum/company/ui/CompanyDetailsScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompanyDetailsViewModel.kt
  feature/company/src/main/res/values/strings.xml
  feature/review/build.gradle.kts
  feature/review/src/main/java/team/retum/review/navigation/ReviewDetailsNavigation.kt
  feature/review/src/main/java/team/retum/review/navigation/ReviewsNavigation.kt
  feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
  feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
  feature/review/src/main/java/team/retum/review/ui/ReviewsScreen.kt
  feature/review/src/main/java/team/retum/review/viewmodel/ReviewDetailsViewModel.kt
  feature/review/src/main/java/team/retum/review/viewmodel/ReviewsViewModel.kt
  feature/review/src/main/res/values/strings.xml
Labels: 기능 구현, 퍼블리싱

#122 🔗 :: (#115) 공지사항 상세 기능 구현
  core/data/src/main/java/team/retum/data/repository/notice/NoticeRepository.kt
  core/data/src/main/java/team/retum/data/repository/notice/NoticeRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/notice/NoticeDetailsEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/notice/FetchNoticeDetailsUseCase.kt
  core/network/src/main/java/team/retum/network/api/NoticeApi.kt
  core/network/src/main/java/team/retum/network/datasource/notice/NoticeDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/notice/NoticeDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/RequestUrls.kt
  core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticeDetailsResponse.kt
  feature/notice/src/main/java/team/retum/jobis/notice/navigation/NoticeDetailsNavigation.kt
  feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
  feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
Labels: 기능 구현

#123 🔗 :: (#119) 홈 화면 미구현 기능 구현
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/common/src/main/java/team/retum/common/model/ReApplyData.kt
  core/domain/src/main/java/team/retum/usecase/entity/application/AppliedCompaniesEntity.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchAppliedCompaniesResponse.kt
  feature/application/src/main/java/team/retum/jobis/application/navigation/ApplicationNavigation.kt
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
Labels: 기능 구현

#125 🔗 :: (#118) 버그 제보 api 연동
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/bug/BugRepository.kt
  core/data/src/main/java/team/retum/data/repository/bug/BugRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/usecase/bug/ReportBugUseCase.kt
  core/network/src/main/java/team/retum/network/api/BugApi.kt
  core/network/src/main/java/team/retum/network/datasource/bug/RemoteBugDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/bug/RemoteBugDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/team/retum/network/model/request/bug/ReportBugRequest.kt
  feature/bug/build.gradle.kts
  feature/bug/src/androidTest/java/team/retum/bug/ExampleInstrumentedTest.kt
  feature/bug/src/main/java/team/retum/bug/navigation/ReportBugNavigation.kt
  feature/bug/src/main/java/team/retum/bug/ui/ReportBugScreen.kt
  feature/bug/src/main/java/team/retum/bug/viewmodel/ReportBugViewModel.kt
  feature/bug/src/main/res/values/strings.xml
  feature/bug/src/test/java/team/retum/bug/ExampleUnitTest.kt
Labels: 기능 구현

#130 🔗 :: (#129) tab bar 리컴포지션 최적화
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/tab/TabBar.kt
  feature/notification/src/main/java/team/retum/notification/viewmodel/NotificationsViewModel.kt
Labels: 리팩토링

#133 🔗 :: (#127) 유저 프로필 사진 변경 기능 구현
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomMenu.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepository.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/usecase/student/EditProfileImageUseCase.kt
  core/network/src/main/java/team/retum/network/api/StudentApi.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/model/request/student/EditProfileImageRequest.kt
  feature/mypage/src/main/java/team/retum/jobis/ui/MyPageScreen.kt
  feature/mypage/src/main/java/team/retum/jobis/viewmodel/MyPageViewModel.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: 기능 구현

#137 🔗 :: (#136) 기업검색 상세
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  feature/company/src/main/java/team/retum/company/navigation/SearchCompaniesNavigation.kt
  feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/ui/SearchCompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompanyViewModel.kt
  feature/company/src/main/res/values/strings.xml
  feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
  feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticesViewModel.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentFilterScreen.kt
  feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
Labels: 버그

#141 🔗 :: (#132) 모집의뢰서 상세 데이터 수정
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
Labels: 버그

#140 🔗 :: (#131) 쟈동 로그인 404 예외 처리
  feature/splash/src/main/java/team/retum/jobis/splash/viewmodel/SplashViewModel.kt
Labels: 버그, 리팩토링

#139 🔗 :: (#135) 공지사항 상세 네비게이션 수정
  core/domain/src/main/java/team/retum/usecase/entity/notice/NoticesEntity.kt
  core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticeDetailsResponse.kt
  core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticesResponse.kt
  feature/notice/src/main/java/team/retum/jobis/notice/navigation/NoticeDetailsNavigation.kt
  feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
  feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticesScreen.kt
  feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
  feature/notice/src/main/res/values/string.xml
Labels: 기능 구현

#151 🔗 :: (#142) 인 앱 업데이트 기능 구현
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 빌드, 기능 구현

#155 🔗 :: (#154) anr 버그
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/SearchRecruitmentScreen.kt
  gradle/libs.versions.toml
Labels: 버그

#158 🔗 :: (#143) 기업 상세 모집의뢰서 상세 내비게이션 기능 구현
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/domain/src/main/java/team/retum/usecase/entity/RecruitmentDetailsEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/company/CompanyDetailsEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/recruitment/FetchRecruitmentDetailsUseCase.kt
  feature/company/src/main/java/team/retum/company/navigation/CompanyDetailsNavigation.kt
  feature/company/src/main/java/team/retum/company/ui/CompanyDetailsScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompanyDetailsViewModel.kt
  feature/company/src/main/res/values/strings.xml
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentDetailsViewModel.kt
Labels: 버그, 리팩토링

#159 🔗 :: (#148) notificationid 버그
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/common/src/main/java/team/retum/common/enums/AlarmType.kt
  core/domain/src/main/java/team/retum/usecase/entity/notification/NotificationsEntity.kt
  core/network/src/main/java/team/retum/network/model/response/notification/FetchNotificationsResponse.kt
  feature/application/src/main/java/team/retum/jobis/application/ui/ApplicationScreen.kt
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
  feature/notification/build.gradle.kts
  feature/notification/src/main/java/team/retum/notification/di/TokenManagerModule.kt
  feature/notification/src/main/java/team/retum/notification/model/NotificationDetailData.kt
  feature/notification/src/main/java/team/retum/notification/navigation/NotificationsNavigation.kt
  feature/notification/src/main/java/team/retum/notification/ui/NotificationsScreen.kt
  feature/notification/src/main/java/team/retum/notification/viewmodel/NotificationsViewModel.kt
Labels: 버그, 리팩토링

#167 🔗 :: (#165) 공지사항 날짜 변경
  core/domain/src/main/java/team/retum/usecase/entity/notice/NoticeDetailsEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/notice/NoticesEntity.kt
Labels: 버그

#170 🔗 :: (#156) 모집의뢰서 페이지 삭제 버그
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/button/JobisIconButton.kt
  core/domain/src/main/java/team/retum/usecase/entity/RecruitmentsEntity.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentContent.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
Labels: 버그, 리팩토링

#173 🔗 :: (#144) 상세로 이동
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  feature/bookmark/src/main/java/team/retum/bookmark/navigation/BookmarkNavigation.kt
  feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
  feature/bookmark/src/main/java/team/retum/bookmark/viewmodel/BookmarkViewModel.kt
  feature/bookmark/src/main/res/values/strings.xml
Labels: 버그

#172 🔗 :: (#164) 면접후기 작성 안 해도 넘어가지는 버그
  feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
  feature/review/src/main/java/team/retum/review/viewmodel/PostReviewViewModel.kt
Labels: 버그

#175 🔗 :: (#171) 면접 후기 상세 버그
  core/domain/src/main/java/team/retum/usecase/entity/FetchReviewsEntity.kt
  feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
Labels: 버그

#174 🔗 :: (#161) fcm notification 만들기
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/retum/jobisandroidv2/service/JobisMessagingService.kt
  core/common/src/main/java/team/retum/common/utils/CheckNotificationPermission.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/JobisIcon.kt
  core/design-system/src/main/res/drawable/app_logo.png
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
  feature/landing/src/main/res/values/strings.xml
  feature/notification/src/main/java/team/retum/notification/util/NotificationManager.kt
Labels: 기능 구현

#176 🔗 :: (#145) 모집의뢰서 상세 포지션 클릭 효과 변경
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
Labels: 버그

#182 🔗 :: (#181) 필터 고치기
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentContent.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
Labels: 버그

#184 🔗 :: (#180) 공지사항 아이콘 변경
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/JobisIcon.kt
  core/design-system/src/main/res/drawable/ic_notice.xml
  feature/mypage/src/main/java/team/retum/jobis/ui/MyPageScreen.kt
  feature/mypage/src/main/res/drawable/ic_loud_speaker.png
Labels: 버그

#185 🔗 :: (#146) 지원 내역 클릭 시 모집의뢰서 상세 조회 기능 구현
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/ApplyCompanyItem.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
Labels: 버그, 리팩토링, 기능 구현

#186 🔗 :: (#179) 서버 점검 다이얼로그 띄우기
  core/common/src/main/java/team/retum/common/exception/RequestExceptions.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/dialog/JobisDialog.kt
  core/network/src/main/java/team/retum/network/util/RequestHandler.kt
  feature/splash/src/main/java/team/retum/jobis/splash/ui/SplashScreen.kt
  feature/splash/src/main/java/team/retum/jobis/splash/viewmodel/SplashViewModel.kt
  feature/splash/src/main/res/values/string.xml
Labels: 리팩토링

#187 🔗 :: (#149) 재지원하기 api 연결
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/common/build.gradle.kts
  core/common/src/main/java/team/retum/common/model/ApplicationData.kt
  core/common/src/main/java/team/retum/common/model/ReApplyData.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepository.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/usecase/application/ReApplyCompanyUseCase.kt
  core/network/src/main/java/team/retum/network/api/ApplicationApi.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSourceImpl.kt
  feature/application/src/main/java/team/retum/jobis/application/model/CompanyInfo.kt
  feature/application/src/main/java/team/retum/jobis/application/navigation/ApplicationNavigation.kt
  feature/application/src/main/java/team/retum/jobis/application/ui/ApplicationScreen.kt
  feature/application/src/main/java/team/retum/jobis/application/viewmodel/ApplicationViewModel.kt
  feature/application/src/main/res/values/strings.xml
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
Labels: 리팩토링, 기능 구현

#190 🔗 :: (#189) 1.0.1 배포
  app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
  app/src/main/res/values-night/themes.xml
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 빌드, 리팩토링

#191 🔗 :: (#183) 연봉 정보 삭제
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentContent.kt
Labels: 버그

#192 🔗 :: (#153) 자동 로그인 안되면 랜딩페이지만 보이는 현상
  core/common/src/main/java/team/retum/common/exception/RequestExceptions.kt
  core/network/src/main/java/team/retum/network/util/RequestHandler.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
  feature/signin/src/main/res/values/strings.xml
  feature/signup/src/main/java/team/retum/signup/ui/TermsScreen.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/TermsViewModel.kt
  feature/signup/src/main/res/values/strings.xml
  feature/splash/src/main/java/team/retum/jobis/splash/ui/SplashScreen.kt
  feature/splash/src/main/java/team/retum/jobis/splash/viewmodel/SplashViewModel.kt
  feature/splash/src/main/res/values/string.xml
Labels: 버그, 기능 구현

#194 🔗 :: (#193) 홈 화면 취업률 수정
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
Labels: 버그, 리팩토링

#196 🔗 :: (#195) 카드 클릭 이벤트 수정
  buildSrc/src/main/kotlin/ProjectProperties.kt
  feature/home/src/main/java/team/retum/home/ui/ApplyCompanyItem.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
Labels: 리팩토링

#198 🔗 :: (#197) 모집기간 옵셔널
  buildSrc/src/main/kotlin/ProjectProperties.kt
  core/domain/src/main/java/team/retum/usecase/entity/RecruitmentDetailsEntity.kt
  core/network/src/main/java/team/retum/network/model/response/FetchRecruitmentDetailsResponse.kt
  feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentContent.kt
Labels: 버그, 리팩토링

#200 🔗 :: (#199) 텍스트 오타 수정
  feature/recruitment/src/main/res/values/strings.xml
Labels: 버그

#203 🔗 :: (#201) 서버 타임아웃 예외 처리
  core/common/src/main/java/team/retum/common/exception/RequestExceptions.kt
  core/network/src/main/java/team/retum/network/util/RequestHandler.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
  feature/signin/src/main/res/values/strings.xml
  feature/signup/src/main/java/team/retum/signup/ui/TermsScreen.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/TermsViewModel.kt
  feature/signup/src/main/res/values/strings.xml
  feature/splash/src/main/java/team/retum/jobis/splash/viewmodel/SplashViewModel.kt
Labels: 기능 구현

#205 🔗 :: (#204) 필터 페이징 이슈
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
  feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
Labels: 버그

#206 🔗 :: (#188) 다크 모드 색상 변경
  app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/button/ButtonColors.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/button/JobisButton.kt
  core/design-system/src/main/res/drawable/bg_toast.xml
  core/design-system/src/main/res/layout/jobis_toast.xml
  core/design-system/src/main/res/values-night/colors.xml
  core/design-system/src/main/res/values/colors.xml
  feature/bug/src/main/java/team/retum/bug/ui/ReportBugScreen.kt
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
  feature/landing/src/main/res/raw/splash_black.json
  feature/landing/src/main/res/raw/splash_white.json
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/splash/src/main/java/team/retum/jobis/splash/ui/SplashScreen.kt
  feature/splash/src/main/res/drawable/ic_black_jobis.png
  feature/splash/src/main/res/drawable/ic_black_team_return.png
  feature/splash/src/main/res/drawable/ic_white_jobis.png
  feature/splash/src/main/res/drawable/ic_white_team_return.png
Labels: 버그
