Repository Team-return/JOBIS-ANDROID-V2, pull requests merged in 2024-02, with the labels that each got.

#28 🔗 :: (#13) 로그인 비즈니스 로직 작성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/CommonGradlePlugin.kt
  buildSrc/src/main/kotlin/ComposeGradlePlugin.kt
  buildSrc/src/main/kotlin/GradlePluginExtensions.kt
  core/common/build.gradle.kts
  core/common/src/main/java/team/retum/common/PlatformType.kt
  core/common/src/main/java/team/retum/common/base/BaseViewModel.kt
  core/common/src/main/java/team/retum/common/exception/RequestExceptions.kt
  core/data/build.gradle.kts
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/UserRepository.kt
  core/data/src/main/java/team/retum/data/repository/UserRepositoryImpl.kt
  core/domain/build.gradle.kts
  core/domain/src/main/java/team/retum/usecase/SignInUseCase.kt
  core/network/build.gradle.kts
  core/network/src/main/java/team/retum/network/api/UserApi.kt
  core/network/src/main/java/team/retum/network/datasource/UserDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/UserDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/DataSourceModule.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RequestUrls.kt
  core/network/src/main/java/team/retum/network/model/request/SignInRequest.kt
  core/network/src/main/java/team/retum/network/model/response/TokenResponse.kt
  core/network/src/main/java/team/retum/network/util/RequestHandler.kt
  core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
  feature/landing/build.gradle.kts
  feature/landing/src/main/java/team/retum/landing/LandingScreen.kt
  feature/signin/build.gradle.kts
  feature/signin/src/main/java/team/retum/signin/SignInScreen.kt
  feature/signin/src/main/java/team/retum/signin/SignInViewModel.kt
  feature/signin/src/main/res/values/strings.xml
  feature/signup/build.gradle.kts
  gradle/libs.versions.toml
Labels: 기능 구현

#27 🔗 :: (#24) 비밀번호 설정 스크린 퍼블리싱
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputEmailScreen.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputPersonalInfoScreen.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SettingPasswordScreen.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/team/retum/signup/ui/InputEmailScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SettingPasswordScreen.kt
  feature/signup/src/main/res/values/strings.xml
Labels: 퍼블리싱

#33 🔗 :: (#32)패키지 조정
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  feature/landing/src/main/java/team/retum/landing/navigation/LandingNavigation.kt
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
  feature/signin/src/main/java/team/retum/signin/navigation/SignInNavigation.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputEmailNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputPersonalInfoNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SettingPasswordNavigation.kt
Labels: 리팩토링

#48 🔗 :: (#46) 프로필 사진 선택 스크린 퍼블리싱
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  core/common/src/main/res/drawable/ic_person.png
  feature/signup/src/main/java/team/retum/signup/navigation/SetProfileNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetProfileScreen.kt
  feature/signup/src/main/res/drawable/ic_pencil.xml
  feature/signup/src/main/res/values/strings.xml
Labels: 퍼블리싱

#49 🔗 :: (#47) 알림 페이지 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
  feature/.DS_Store
  feature/alarm/.gitignore
  feature/alarm/build.gradle.kts
  feature/alarm/src/androidTest/java/team/retum/alarm/ExampleInstrumentedTest.kt
  feature/alarm/src/main/java/team/retum/alarm/navigation/AlarmNavigation.kt
  feature/alarm/src/main/java/team/retum/alarm/ui/AlarmScreen.kt
  feature/alarm/src/main/res/values/strings.xml
  feature/alarm/src/test/java/team/retum/alarm/ExampleUnitTest.kt
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/landing/src/main/java/team/retum/landing/navigation/LandingNavigation.kt
  feature/signin/src/main/java/team/retum/signin/navigation/SignInNavigation.kt
  settings.gradle.kts
Labels: 기능 구현

#52 🔗 :: (#51) 약관 동의 스크린 퍼블리싱
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SetProfileNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/TermsNavigation.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetProfileScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/TermsScreen.kt
  feature/signup/src/main/res/values/strings.xml
Labels: 퍼블리싱

#53 🔗 :: (#38) 북마크 스크린 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
  feature/alarm/src/main/java/team/retum/alarm/ui/AlarmScreen.kt
  feature/bookmark/.gitignore
  feature/bookmark/build.gradle.kts
  feature/bookmark/src/androidTest/java/team/retum/bookmark/ExampleInstrumentedTest.kt
  feature/bookmark/src/main/java/team/retum/bookmark/navigation/BookmarkNavigation.kt
  feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
  feature/bookmark/src/main/res/drawable/ic_delete.xml
  feature/bookmark/src/main/res/drawable/ic_empty_bookmark.png
  feature/bookmark/src/main/res/values/strings.xml
  feature/bookmark/src/test/java/team/retum/bookmark/ExampleUnitTest.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputEmailNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputPersonalInfoNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SetPasswordNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/team/retum/signup/ui/InputEmailScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/InputPersonalInfoScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SelectGenderScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetPasswordScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetProfileScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/TermsScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 기능 구현

#57 🔗 :: (#36) 모집의뢰서 리스트 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomMenu.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
  feature/recruitment/.gitignore
  feature/recruitment/build.gradle.kts
  feature/recruitment/src/androidTest/java/team/retum/recruitment/ExampleInstrumentedTest.kt
  feature/recruitment/src/main/java/team/retum/recruitment/RecruitmentsNavigation.kt
  feature/recruitment/src/main/java/team/retum/recruitment/RecruitmentsScreen.kt
  feature/recruitment/src/main/res/values/strings.xml
  feature/recruitment/src/test/java/team/retum/recruitment/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 버그

#58 🔗 :: (#43) 북마크 서버 연동
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/BookmarkRepository.kt
  core/data/src/main/java/team/retum/data/repository/BookmarkRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/BookmarksEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/bookmark/BookmarkRecruitmentUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/bookmark/BookmarkUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/user/SignInUseCase.kt
  core/network/build.gradle.kts
  core/network/src/main/java/team/retum/network/api/BookmarkApi.kt
  core/network/src/main/java/team/retum/network/datasource/BookmarkDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/BookmarkDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/DataSourceModule.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/model/response/BookmarksResponse.kt
  core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
  feature/bookmark/build.gradle.kts
  feature/bookmark/src/main/java/team/retum/bookmark/navigation/BookmarkNavigation.kt
  feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
  feature/bookmark/src/main/java/team/retum/bookmark/viewmodel/BookmarkViewModel.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
  gradle/libs.versions.toml
Labels: 기능 구현

#59 🔗 :: (#39) 버그 제보 스크린 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  core/common/src/main/java/team/retum/common/enums/DevelopmentArea.kt
  feature/bug/.gitignore
  feature/bug/build.gradle.kts
  feature/bug/src/androidTest/java/team/retum/bug/ExampleInstrumentedTest.kt
  feature/bug/src/main/java/team/retum/bug/ReportBugNavigation.kt
  feature/bug/src/main/java/team/retum/bug/ReportBugScreen.kt
  feature/bug/src/main/res/drawable/ic_arrow_down.xml
  feature/bug/src/main/res/drawable/ic_photo.xml
  feature/bug/src/main/res/values/strings.xml
  feature/bug/src/test/java/team/retum/bug/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 퍼블리싱

#61 🔗 :: (#37) 관심분야 스크린 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  feature/interests/.gitignore
  feature/interests/build.gradle.kts
  feature/interests/src/androidTest/java/team/retum/jobis/interests/ExampleInstrumentedTest.kt
  feature/interests/src/main/java/team/retum/jobis/interests/navigation/InterestsNavigation.kt
  feature/interests/src/main/java/team/retum/jobis/interests/ui/InterestsScreen.kt
  feature/interests/src/main/res/drawable/ic_check.xml
  feature/interests/src/main/res/values/strings.xml
  feature/interests/src/test/java/team/retum/jobis/interests/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 퍼블리싱

#65 🔗 :: (#64) 비밀번호 변경 스크린 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/button/JobisButton.kt
  feature/change-password/.gitignore
  feature/change-password/build.gradle.kts
  feature/change-password/src/androidTest/java/team/retum/change_password/ExampleInstrumentedTest.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/navigation/ConfirmPasswordNavigation.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/navigation/ResetPasswordNavigation.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/ui/ConfirmPasswordScreen.kt
  feature/change-password/src/main/java/team/retum/jobis/change_password/ui/ResetPasswordScreen.kt
  feature/change-password/src/main/res/values/strings.xml
  feature/change-password/src/test/java/team/retum/change_password/ExampleUnitTest.kt
  feature/interests/src/main/java/team/retum/jobis/interests/ui/InterestsScreen.kt
  feature/signin/src/main/java/team/retum/signin/navigation/SignInNavigation.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signin/src/main/res/values/strings.xml
  feature/verify-email/.gitignore
  feature/verify-email/build.gradle.kts
  feature/verify-email/src/main/java/team/retum/jobis/verify_email/navigation/VerifyEmailNavigation.kt
  feature/verify-email/src/main/java/team/retum/jobis/verify_email/ui/VerifyEmailScreen.kt
  feature/verify-email/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 퍼블리싱

#67 🔗 :: (#55) 마이페이지 스크린 퍼블리싱
  .DS_Store
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomMenu.kt
  feature/.DS_Store
  feature/mypage/.DS_Store
  feature/mypage/.gitignore
  feature/mypage/build.gradle.kts
  feature/mypage/src/.DS_Store
  feature/mypage/src/main/java/team/returm/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
  feature/mypage/src/main/res/drawable/ic_loud_speaker.png
  feature/mypage/src/main/res/drawable/ic_user_profile.jpg
  feature/mypage/src/main/res/values/strings.xml
  feature/mypage/src/test/.DS_Store
  feature/mypage/src/test/java/.DS_Store
  settings.gradle.kts
Labels: 기능 구현

#69 🔗 :: (#66) 반려 사유 바텀 시트 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/common/src/main/java/team/retum/common/enums/ApplyStatus.kt
  core/common/src/main/java/team/retum/common/enums/PlatformType.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/card/JobisCard.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/tab/TabBar.kt
  core/network/src/main/java/team/retum/network/model/request/SignInRequest.kt
  feature/alarm/src/main/java/team/retum/alarm/ui/AlarmScreen.kt
  feature/alarm/src/main/res/values/strings.xml
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/res/values/strings.xml
  feature/interests/src/main/java/team/retum/jobis/interests/ui/InterestsScreen.kt
  feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
  feature/recruitment/src/main/java/team/retum/recruitment/RecruitmentsNavigation.kt
Labels: 퍼블리싱

#74 🔗 :: (#71) 기업탐색 구현
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/company/CompanyRepository.kt
  core/data/src/main/java/team/retum/data/repository/company/CompanyRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/entity/CompaniesEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/CompanyCountEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/company/FetchCompaniesUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/company/FetchCompanyCountUseCase.kt
  core/network/src/main/java/team/retum/network/api/CompanyApi.kt
  core/network/src/main/java/team/retum/network/datasource/company/CompanyDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/company/CompanyDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/DataSourceModule.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/model/response/FetchCompaniesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchCompanyPageCountResponse.kt
  feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
  feature/bookmark/src/main/res/drawable/ic_delete.xml
  feature/company/build.gradle.kts
  feature/company/src/main/java/team/retum/company/navigation/CompaniesNavigation.kt
  feature/company/src/main/java/team/retum/company/navigation/SearchCompaniesNavigation.kt
  feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/ui/SearchCompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompanyViewModel.kt
  feature/company/src/main/res/drawable/ic_empty_company.png
  feature/company/src/main/res/values/strings.xml
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 기능 구현, 퍼블리싱

#78 🔗 :: (#76) 공지사항 상세 페이지 퍼블리싱
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  feature/notification/.gitignore
  feature/notification/build.gradle.kts
  feature/notification/src/main/java/team/retum/jobis/notification/navigation/NotificationDetailsNavigation.kt
  feature/notification/src/main/java/team/retum/jobis/notification/ui/NotificationDetailsScreen.kt
  feature/notification/src/main/res/drawable/ic_download.xml
  feature/notification/src/main/res/values/string.xml
  settings.gradle.kts
Labels: 퍼블리싱

#77 🔗 :: (#72) 지원하기 퍼블리싱
  app/src/main/java/team/retum/jobisandroidv2/ApplicationNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/ApplicationScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
Labels: 퍼블리싱

#79 🔗 :: (#44) 마이페이지 스크린 연결
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomMenu.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/button/ButtonColors.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/button/JobisButton.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/dialog/JobisDialog.kt
  feature/bug/src/main/java/team/retum/bug/ReportBugNavigation.kt
  feature/bug/src/main/java/team/retum/bug/ReportBugScreen.kt
  feature/interests/src/main/java/team/retum/jobis/interests/navigation/InterestsNavigation.kt
  feature/interests/src/main/java/team/retum/jobis/interests/ui/InterestsScreen.kt
  feature/mypage/src/main/java/team/returm/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: 기능 구현

#85 🔗 :: (#40) 회원가입 비즈니스 로직 작성
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/ComposeGradlePlugin.kt
  core/common/src/main/java/team/retum/common/enums/AuthCodeType.kt
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/common/src/main/java/team/retum/common/utils/TimerUtil.kt
  core/data/build.gradle.kts
  core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
  core/data/src/main/java/team/retum/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/team/retum/data/repository/auth/AuthRepositoryImpl.kt
  core/data/src/main/java/team/retum/data/repository/bookmark/BookmarkRepository.kt
  core/data/src/main/java/team/retum/data/repository/bookmark/BookmarkRepositoryImpl.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepository.kt
  core/data/src/main/java/team/retum/data/repository/student/StudentRepositoryImpl.kt
  core/domain/src/main/java/team/retum/usecase/usecase/auth/AuthorizeAuthenticationCodeUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/auth/SendAuthenticationCodeUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/bookmark/BookmarkRecruitmentUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/bookmark/BookmarkUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/student/CheckStudentExistsUseCase.kt
  core/network/src/main/java/team/retum/network/api/AuthApi.kt
  core/network/src/main/java/team/retum/network/api/StudentApi.kt
  core/network/src/main/java/team/retum/network/datasource/auth/RemoteAuthDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/auth/RemoteAuthDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/datasource/bookmark/BookmarkDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/bookmark/BookmarkDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/team/retum/network/model/request/auth/SendAuthenticationCodeRequest.kt
  feature/signup/build.gradle.kts
  feature/signup/src/main/java/team/retum/signup/model/SignUpData.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputEmailNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputPersonalInfoNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SetPasswordNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/team/retum/signup/ui/InputEmailScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/InputPersonalInfoScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetPasswordScreen.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/InputEmailViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/InputPersonalInfoViewModel.kt
  feature/signup/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 기능 구현

#84 🔗 :: (#81) 공지 리스트 페이지 퍼블리싱
  .DS_Store
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/JobisIcon.kt
  core/design-system/src/main/res/drawable/ic_arrow_right.xml
  feature/mypage/src/main/java/team/returm/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
  feature/notification/src/main/java/team/retum/jobis/notification/navigation/NotificationsListNavigation.kt
  feature/notification/src/main/java/team/retum/jobis/notification/ui/NotificationListScreen.kt
Labels: 퍼블리싱

#87 🔗 :: (#86) 빌드 오류 수정
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
Labels: 버그, 리팩토링

#90 🔗 :: (#88) ktlint 자동화
  .editorconfig
  .github/workflows/android.yml
  app/build.gradle.kts
  app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 빌드
