Repository Team-return/JOBIS-ANDROID-V2, pull requests merged in 2024-07, with the labels that each got.

#274 🔗 :: (#272) 테스트 코드 개선
  core/design-system/build.gradle.kts
  core/design-system/src/androidTest/java/team/retum/jobisdesignsystemv2/JobisButtonTest.kt
  feature/company/build.gradle.kts
  feature/company/src/androidTest/java/team/retum/company/CompaniesViewModelTest.kt
  gradle/libs.versions.toml
Labels: 테스트

#276 🔗 :: (#268) 약관 url 환경변수로 이동
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signup/build.gradle.kts
  feature/signup/src/main/java/team/retum/signup/ui/TermsScreen.kt
Labels: 빌드, 리팩토링

#278 🔗 :: (#277) ci 개선
  .github/dependabot.yml
Labels: 빌드

#287 🔗 :: (#286) dependabot 수정
  .github/dependabot.yml
Labels: 빌드

#289 merge :: (#288) 파이프라인 병렬화
  .github/workflows/android-ci.yml
Labels: 빌드

#292 🔗 :: (#291) 코드 문서화
  app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
  buildSrc/src/main/kotlin/CommonGradlePlugin.kt
  buildSrc/src/main/kotlin/ComposeGradlePlugin.kt
  core/common/src/main/java/team/retum/common/base/BaseViewModel.kt
  core/network/src/main/java/team/retum/network/util/RequestHandler.kt
  core/network/src/main/java/team/retum/network/util/TokenAuthenticator.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
Labels: 문서

#294 🔗 :: (#293) 디자인 시스템 코드 문서화
  core/design-system/build.gradle.kts
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/card/JobisCard.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/popup/JobisPopup.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/textfield/JobisTextField.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/toast/JobisToast.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/utils/Clickable.kt
Labels: 문서

#296 🔗 :: (#295) s3 url 변경
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
Labels: 버그, 리팩토링
