Repository Team-return/JOBIS-ANDROID-V2, pull requests merged in 2024-04, with the labels that each got.

#208 🔗 :: (#207) 바텀 내비게이션 애니메이션 설정
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 버그, 기능 구현

#210 🔗 :: (#209) 앱 아이콘 변경
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 리팩토링

#212 🔗 :: (#211) list 타입 변경
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
Labels: 리팩토링

#215 🔗 :: (#213) 토큰 리프레시 구현
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/util/TokenAuthenticator.kt
  core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
Labels: 리팩토링, 기능 구현

#219 🔗 :: (#218) 기업 리스트 로직 리팩토링
  core/domain/src/main/java/team/retum/usecase/entity/CompaniesEntity.kt
  feature/company/src/main/java/team/retum/company/component/CompanyItem.kt
  feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/ui/SearchCompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompaniesViewModel.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompanyViewModel.kt
  feature/company/src/main/res/values/strings.xml
Labels: 리팩토링

#221 🔗 :: (#220) 컬러 팔레트 수정
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/JobisColor.kt
  feature/mypage/src/main/java/team/retum/jobis/ui/MyPageScreen.kt
Labels: 리팩토링

#224 🔗 :: (#222) 기업 리스트 스켈레톤 처리
  core/domain/src/main/java/team/retum/usecase/entity/CompaniesEntity.kt
  feature/company/src/main/java/team/retum/company/component/CompanyItem.kt
  feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompaniesViewModel.kt
Labels: 리팩토링, 기능 구현

#226 🔗 :: (#225) 모집의뢰서 페이징 리팩토링
  core/common/src/main/java/team/retum/common/enums/MilitarySupport.kt
  core/domain/src/main/java/team/retum/usecase/entity/RecruitmentsEntity.kt
  feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
  feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/ui/SearchCompaniesScreen.kt
  feature/company/src/main/java/team/retum/company/viewmodel/CompaniesViewModel.kt
  feature/company/src/main/res/values/strings.xml
  feature/recruitment/build.gradle.kts
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/SearchRecruitmentScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
  feature/recruitment/src/main/res/values/strings.xml
Labels: 리팩토링, 기능 구현

#230 🔗 :: (#229) 컴포즈 함수 수명주기 테스트
  core/common/src/main/java/team/retum/common/utils/ComposableLifecycle.kt
Labels: 테스트

#234 🔗 :: (#233) 회원가입 jsondecodingexception 수정
  feature/signup/src/main/java/team/retum/signup/model/SignUpData.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/SetPasswordViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/SetProfileViewModel.kt
  feature/signup/src/main/java/team/retum/signup/viewmodel/TermsViewModel.kt
Labels: 버그

#238 🔗 :: (#237) 랜딩 페이지 개선
  feature/landing/src/main/res/raw/splash_white.json
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
Labels: 버그

#228 🔗 :: (#223) 비밀번호 특수문자 예시 적용
  feature/change-password/src/main/java/team/retum/jobis/change/password/ui/ComparePasswordScreen.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/ui/ResetPasswordScreen.kt
  feature/change-password/src/main/java/team/retum/jobis/change/password/viewmodel/ComparePasswordViewModel.kt
  feature/change-password/src/main/res/values/strings.xml
  feature/signup/src/main/res/values/strings.xml
Labels: 리팩토링

#236 🔗 :: (#235) url encoding
  buildSrc/src/main/kotlin/ProjectProperties.kt
  feature/home/src/main/java/team/retum/home/ui/ApplyCompanyItem.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/signup/src/main/java/team/retum/signup/navigation/InputEmailNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SelectGenderNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SetPasswordNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/SetProfileNavigation.kt
  feature/signup/src/main/java/team/retum/signup/navigation/TermsNavigation.kt
Labels: 리팩토링

#240 🔗 :: (#239) 코드 리팩토링
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/domain/src/main/java/team/retum/usecase/entity/BookmarksEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/CompaniesEntity.kt
  core/domain/src/main/java/team/retum/usecase/entity/company/ReviewableCompaniesEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/auth/SendAuthenticationCodeUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/user/SignInUseCase.kt
  feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
  feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
  feature/company/src/main/java/team/retum/company/model/CompanyInfoData.kt
  feature/company/src/main/java/team/retum/company/ui/CompanyDetailsScreen.kt
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
  feature/landing/src/main/res/values/strings.xml
  feature/mypage/src/main/java/team/retum/jobis/ui/MyPageScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentFilterScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
Labels: 리팩토링

#241 🔗 :: (#231) 북마크 아이콘 색상 변경
  .github/CODEOWNERS
  buildSrc/src/main/kotlin/ProjectProperties.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
Labels: 리팩토링

#242 🔗 :: (#232) 지원 불가능 텍스트 변경
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/recruitment/src/main/res/values/strings.xml
Labels: 리팩토링

#244 🔗 :: (#243) R8 적용
  app/build.gradle.kts
  app/proguard-rules.pro
  feature/change-password/src/main/res/values/strings.xml
  feature/home/src/main/res/values/strings.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/recruitment/src/main/res/drawable/ic_arrow_up.xml
  feature/recruitment/src/main/res/values/strings.xml
  feature/verify-email/src/main/res/values/strings.xml
Labels: 빌드

#251 🔗 :: (#250) 빌드 오류 수정
  settings.gradle.kts
Labels: 버그

#247 🔗 :: (#246) ci 최적화
  .github/workflows/android-ci.yml
  app/build.gradle.kts
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/tab/TabBar.kt
  gradle.properties
Labels: 빌드

#253 🔗 :: (#252) 테스트 환경 세팅
  buildSrc/src/main/kotlin/CommonGradlePlugin.kt
  buildSrc/src/main/kotlin/ComposeGradlePlugin.kt
  buildSrc/src/main/kotlin/GradlePluginExtensions.kt
  core/common/src/main/java/team/retum/common/HiltTestRunner.kt
  gradle/libs.versions.toml
Labels: 빌드

#227 🔗 :: (#166) 공지사항 상세 다운로드 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/provider_paths_app.xml
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/JobisIcon.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/popup/JobisPopup.kt
  core/design-system/src/main/res/anim/popup_slide_in.xml
  core/design-system/src/main/res/anim/popup_slide_out.xml
  core/design-system/src/main/res/drawable/bg_popup.xml
  core/design-system/src/main/res/drawable/bg_popup_button.xml
  core/design-system/src/main/res/drawable/ic_download.xml
  core/design-system/src/main/res/layout/jobis_popup.xml
  core/design-system/src/main/res/values-night/colors.xml
  core/design-system/src/main/res/values/colors.xml
  feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
  feature/notice/src/main/java/team/retum/jobis/notice/util/OpenDownloadFile.kt
  feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
  feature/notice/src/main/res/values/string.xml
Labels: 기능 구현

#254 🔗 :: (#217) room 세팅
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/local/build.gradle.kts
  core/local/src/main/java/team/retum/jobis/local/database/JobisDatabase.kt
  core/local/src/main/java/team/retum/jobis/local/di/DatabaseModule.kt
  core/local/src/main/java/team/retum/jobis/local/entity/TestEntity.kt
  gradle/libs.versions.toml
Labels: 세팅
