Repository Team-return/JOBIS-ANDROID-V2, pull requests merged in 2024-09, with the labels that each got.

#320 🔗 :: (#318) ci 최적화
  .github/workflows/android-ci.yml
Labels: 세팅

#317 🔗 :: (#313) 알림 강제성 없애기
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
Labels: 리팩토링

#322 🔗 :: (#321) ci/cd 파이프라인 구축
  .gitignore
  app/build.gradle.kts
  app/src/main/play/release-notes/ko-KR/default.txt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 문서, 빌드, 세팅

#323 🔗 :: (#302 )알림 설정 페이지 추가
  app/src/main/java/team/retum/jobisandroidv2/JobisNavigator.kt
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  core/common/src/main/java/team/retum/common/enums/NotificationTopic.kt
  core/data/src/main/java/team/retum/data/repository/notification/NotificationRepository.kt
  core/data/src/main/java/team/retum/data/repository/notification/NotificationRepositoryImpl.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/switches/JobisSwitches.kt
  core/domain/src/main/java/team/retum/usecase/entity/notification/TopicsEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/notification/FetchNotificationSettingsStatusesUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/notification/SettingAllNotificationUseCase.kt
  core/domain/src/main/java/team/retum/usecase/usecase/notification/SettingNotificationUseCase.kt
  core/network/src/main/java/team/retum/network/api/NotificationApi.kt
  core/network/src/main/java/team/retum/network/datasource/notification/NotificationDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/notification/NotificationDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/RequestUrls.kt
  core/network/src/main/java/team/retum/network/model/response/notification/FetchNotificationSettingStatusesResponse.kt
  feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
  feature/mypage/src/main/java/team/retum/jobis/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/team/retum/jobis/ui/MyPageScreen.kt
  feature/mypage/src/main/res/values/strings.xml
  feature/notice/src/main/java/team/retum/jobis/notice/util/OpenDownloadFile.kt
  feature/notification/src/main/java/team/retum/notification/navigation/NotificationSettingNavigation.kt
  feature/notification/src/main/java/team/retum/notification/ui/NotificationSettingScreen.kt
  feature/notification/src/main/java/team/retum/notification/viewmodel/NotificationSettingViewModel.kt
  feature/notification/src/main/res/values/strings.xml
Labels: 기능 구현, 퍼블리싱

#324 🔗 :: (#297) dependabot secret 파일 권한 설정
  .github/workflows/dependabot-ci.yml
Labels: 문서, 세팅

#328 🚀 :: v2.1.0
  app/src/main/play/release-notes/ko-KR/default.txt
Labels: 배포

#330 🚀 :: v2.1.1
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#331 🚀 :: v2.1.1
  .github/workflows/android-production-deploy-play-store.yml
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#332 🚀 :: v2.1.2
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#334 🚀 :: v2.1.2
  app/build.gradle.kts
  app/src/main/play/release-notes/ko-KR/default.txt
Labels: 배포

#335 🚀 :: v2.1.2
  app/build.gradle.kts
  app/src/main/play/release-notes/ko-KR/default.txt
Labels: 배포

#336 🚀 :: v2.1.2
  app/build.gradle.kts
Labels: 배포

#337 🚀 :: v2.1.2
  app/build.gradle.kts
Labels: 배포

#338 🚀 :: 2.1.2
  app/build.gradle.kts
Labels: 배포

#339 🚀 :: v2.1.2
  app/build.gradle.kts
Labels: 배포

#340 🚀 :: v2.1.3
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#341 🚀 :: v2.1.3
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#344 🚀 :: v2.1.3
  app/build.gradle.kts
Labels: 배포

#345 🚀 :: 2.1.3
  .github/workflows/android-ci.yml
  .github/workflows/android-production-deploy-play-store.yml
  app/build.gradle.kts
Labels: 배포

#346 🚀 :: v2.1.4
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#347 🚀 :: v2.1.4
  .github/workflows/android-ci.yml
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#348 🚀 :: v2.1.5
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#349 🚀 :: v2.1.5
  .github/workflows/android-production-deploy-play-store.yml
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#350 🚀 :: v2.1.5
  app/src/main/play/release-notes/ko-KR/default.txt
Labels: 배포

#351 🚀 :: v2.1.5
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
Labels: 배포

#352 🚀 :: v2.1.6
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#353 🚀 :: v2.1.6
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#354 🚀 :: v2.1.7
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#355 🚀 :: v2.1.7
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#356 🚀 :: v2.1.8
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#357 🚀 :: v2.1.8
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#358 🚀 :: v2.1.9
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#360 🚀 :: v2.2.0
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#361 🚀 :: v2.2.0
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#363 🚀 :: v2.1.1
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#362 🚀 :: v2.1.1
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#364 🚀 :: v2.2.2
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#365 🚀 :: v2.2.2
  .github/workflows/android-production-deploy-play-store.yml
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 배포

#370 🔗 :: 368 api implementation으로 변경하기
  .github/workflows/android-ci.yml
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/CommonGradlePlugin.kt
  buildSrc/src/main/kotlin/ComposeGradlePlugin.kt
  buildSrc/src/main/kotlin/GradlePluginExtensions.kt
  core/common/build.gradle.kts
  core/data/build.gradle.kts
  core/design-system/build.gradle.kts
  core/domain/build.gradle.kts
  core/local/build.gradle.kts
  core/network/build.gradle.kts
  feature/application/build.gradle.kts
  feature/bookmark/build.gradle.kts
  feature/bug/build.gradle.kts
  feature/change-password/build.gradle.kts
  feature/company/build.gradle.kts
  feature/home/build.gradle.kts
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/interests/build.gradle.kts
  feature/landing/build.gradle.kts
  feature/landing/src/main/java/team/retum/landing/ui/LandingScreen.kt
  feature/mypage/build.gradle.kts
  feature/notice/build.gradle.kts
  feature/notification/build.gradle.kts
  feature/recruitment/build.gradle.kts
  feature/review/build.gradle.kts
  feature/signin/build.gradle.kts
  feature/signup/build.gradle.kts
  feature/signup/src/main/java/team/retum/signup/ui/SelectGenderScreen.kt
  feature/signup/src/main/java/team/retum/signup/ui/SetProfileScreen.kt
  feature/splash/build.gradle.kts
  feature/verify-email/build.gradle.kts
  gradle/libs.versions.toml
Labels: 빌드

#372 🔗 :: (#367) 배포 설정 상태 변경
  app/build.gradle.kts
Labels: 빌드

#374 🔗 :: (#373) 지원 내역 복사 버그
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
Labels: 버그

#379 🔗 :: (#378) 파이어베이스 performance 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 빌드, 기능 구현

#376 🔗 :: (#369) 인증코드 전송 버그
  core/domain/src/main/java/team/retum/usecase/usecase/auth/AuthorizeAuthenticationCodeUseCase.kt
  feature/verify-email/src/main/java/team/retum/jobis/verify/email/ui/VerifyEmailScreen.kt
  feature/verify-email/src/main/java/team/retum/jobis/verify/email/viewmodel/VerifyEmailViewModel.kt
  feature/verify-email/src/main/res/values/strings.xml
Labels: 버그
