Repository Team-return/JOBIS-ANDROID-V2, pull requests merged in 2024-05, with the labels that each got.

#256 🔗 :: (#30) 로그인 테스트 코드 작성
  .github/workflows/android-ci.yml
  app/build.gradle.kts
  buildSrc/src/main/kotlin/CommonGradlePlugin.kt
  core/common/build.gradle.kts
  core/common/src/androidTest/java/team/retum/common/ExampleInstrumentedTest.kt
  core/common/src/test/java/team/retum/common/ExampleUnitTest.kt
  core/data/build.gradle.kts
  core/data/src/androidTest/java/team/retum/data/ExampleInstrumentedTest.kt
  core/data/src/test/java/team/retum/data/ExampleUnitTest.kt
  core/design-system/build.gradle.kts
  core/design-system/src/androidTest/java/team/retum/jobisdesignsystemv2/ExampleInstrumentedTest.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/button/JobisButton.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/textfield/JobisTextField.kt
  core/design-system/src/test/java/team/retum/jobisdesignsystemv2/ExampleUnitTest.kt
  core/domain/build.gradle.kts
  core/domain/src/androidTest/java/team/retum/domain/ExampleInstrumentedTest.kt
  core/domain/src/test/java/team/retum/domain/ExampleUnitTest.kt
  core/local/build.gradle.kts
  core/network/build.gradle.kts
  core/network/src/androidTest/java/team/retum/network/ExampleInstrumentedTest.kt
  core/network/src/test/java/team/retum/network/ExampleUnitTest.kt
  feature/application/build.gradle.kts
  feature/bookmark/build.gradle.kts
  feature/bookmark/src/androidTest/java/team/retum/bookmark/ExampleInstrumentedTest.kt
  feature/bookmark/src/test/java/team/retum/bookmark/ExampleUnitTest.kt
  feature/bug/build.gradle.kts
  feature/change-password/build.gradle.kts
  feature/company/build.gradle.kts
  feature/home/build.gradle.kts
  feature/home/src/androidTest/java/team/retum/home/ExampleInstrumentedTest.kt
  feature/home/src/test/java/team/retum/home/ExampleUnitTest.kt
  feature/interests/build.gradle.kts
  feature/interests/src/androidTest/java/team/retum/jobis/interests/ExampleInstrumentedTest.kt
  feature/interests/src/test/java/team/retum/jobis/interests/ExampleUnitTest.kt
  feature/landing/build.gradle.kts
  feature/landing/src/androidTest/java/team/retum/landing/ExampleInstrumentedTest.kt
  feature/landing/src/test/java/team/retum/landing/ExampleUnitTest.kt
  feature/mypage/build.gradle.kts
  feature/notice/build.gradle.kts
  feature/notification/build.gradle.kts
  feature/recruitment/build.gradle.kts
  feature/recruitment/src/androidTest/java/team/retum/recruitment/ExampleInstrumentedTest.kt
  feature/recruitment/src/test/java/team/retum/recruitment/ExampleUnitTest.kt
  feature/review/build.gradle.kts
  feature/signin/build.gradle.kts
  feature/signin/src/androidTest/java/team/retum/signin/ExampleInstrumentedTest.kt
  feature/signin/src/androidTest/java/team/retum/signin/SignInScreenTest.kt
  feature/signin/src/debug/java/AndroidManifest.xml
  feature/signin/src/main/java/team/retum/signin/SignInTestActivity.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
  feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
  feature/signin/src/test/java/team/retum/signin/ExampleUnitTest.kt
  feature/signup/build.gradle.kts
  feature/signup/src/androidTest/java/team/retum/signup/ExampleInstrumentedTest.kt
  feature/signup/src/test/java/team/retum/signup/ExampleUnitTest.kt
  feature/splash/build.gradle.kts
  feature/verify-email/build.gradle.kts
Labels: 테스트

#258 🔗 :: (#257) 로그인 액세스 토큰 초기화 버그
  buildSrc/src/main/kotlin/ProjectProperties.kt
  core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
Labels: 버그

#260 🔗 :: (#259) 소수점 포맷 수정
  core/domain/src/main/java/team/retum/usecase/entity/CompaniesEntity.kt
  feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
Labels: 리팩토링

#262 🔗 :: (#261) 데이터 포멧 코드 개선
  core/network/build.gradle.kts
  core/network/src/main/java/team/retum/network/di/NetworkModule.kt
  core/network/src/main/java/team/retum/network/model/request/PostReviewRequest.kt
  core/network/src/main/java/team/retum/network/model/request/application/ApplyCompanyRequest.kt
  core/network/src/main/java/team/retum/network/model/request/auth/SendAuthenticationCodeRequest.kt
  core/network/src/main/java/team/retum/network/model/request/bug/ReportBugRequest.kt
  core/network/src/main/java/team/retum/network/model/request/file/CreatePresignedUrlRequest.kt
  core/network/src/main/java/team/retum/network/model/request/student/ChangePasswordRequest.kt
  core/network/src/main/java/team/retum/network/model/request/student/EditProfileImageRequest.kt
  core/network/src/main/java/team/retum/network/model/request/student/ForgottenPasswordRequest.kt
  core/network/src/main/java/team/retum/network/model/request/student/PostSignUpRequest.kt
  core/network/src/main/java/team/retum/network/model/request/user/SignInRequest.kt
  core/network/src/main/java/team/retum/network/model/response/BookmarksResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchCodesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchCompaniesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchCompanyPageCountResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchRecruitmentDetailsResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchRecruitmentPageCountResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchRecruitmentsResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchReviewDetailResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchReviewsResponse.kt
  core/network/src/main/java/team/retum/network/model/response/FetchStudentInformationResponse.kt
  core/network/src/main/java/team/retum/network/model/response/TokenResponse.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchAppliedCompaniesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchEmploymentCountResponse.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchRejectionReasonResponse.kt
  core/network/src/main/java/team/retum/network/model/response/banner/FetchBannersResponse.kt
  core/network/src/main/java/team/retum/network/model/response/company/FetchCompanyDetailsResponse.kt
  core/network/src/main/java/team/retum/network/model/response/company/FetchReviewableCompaniesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/file/CreatePresignedUrlResponse.kt
  core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticeDetailsResponse.kt
  core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticesResponse.kt
  core/network/src/main/java/team/retum/network/model/response/notification/FetchNotificationsResponse.kt
  core/network/src/main/java/team/retum/network/util/TokenAuthenticator.kt
  gradle/libs.versions.toml
Labels: 리팩토링

#264 🔗 :: (#263) UI draw 속도 개선
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
  feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
Labels: 리팩토링

#267 🔗 :: (#266) 최신 코드로 개선
  app/build.gradle.kts
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
  feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
  feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
  feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
Labels: 리팩토링

#269 🔗 :: (#265) 알림 리스트 수정
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/JobisColor.kt
  core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/Theme.kt
  feature/notification/src/main/java/team/retum/notification/ui/NotificationsScreen.kt
Labels: 리팩토링, 기능 구현
