Repository Team-return/JOBIS-ANDROID-V2, pull requests merged in 2025-04, with the labels that each got.

#456 🔗 :: (#455) 디바이스 토큰 등록 버그 수정
  core/device/src/main/java/team/retum/device/DeviceTokenException.kt
  core/device/src/main/java/team/retum/device/DeviceTokenManager.kt
Labels: 버그

#454 🔗 :: (#453) 알림함 버그 수정
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  core/common/src/main/java/team/retum/common/enums/AlarmType.kt
  feature/notification/src/main/java/team/retum/notification/navigation/NotificationsNavigation.kt
  feature/notification/src/main/java/team/retum/notification/ui/NotificationsScreen.kt
  feature/notification/src/main/java/team/retum/notification/viewmodel/NotificationsViewModel.kt
  feature/notification/src/main/res/values/strings.xml
Labels: 버그

#458 🚀 :: v2.2.9
  .DS_Store
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/retum/jobisandroidv2/JobisApplication.kt
  app/src/main/java/team/retum/jobisandroidv2/JobisNavigator.kt
  app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
  app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
  app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
  app/src/main/java/team/retum/jobisandroidv2/ui/BottomMenu.kt
  app/src/main/play/release-notes/ko-KR/default.txt
  buildSrc/src/main/kotlin/ProjectProperties.kt
  core/common/src/main/java/team/retum/common/enums/AlarmType.kt
  core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepository.kt
  core/data/src/main/java/team/retum/data/repository/application/ApplicationRepositoryImpl.kt
  core/design-system/src/main/res/drawable/ic_computer.png
  core/design-system/src/main/res/drawable/ic_robot.png
  core/design-system/src/main/res/drawable/ic_spanner.png
  core/device/src/main/java/team/retum/device/DeviceTokenException.kt
  core/device/src/main/java/team/retum/device/DeviceTokenManager.kt
  core/domain/src/main/java/team/retum/usecase/entity/application/EmploymentStatusEntity.kt
  core/domain/src/main/java/team/retum/usecase/usecase/application/FetchEmploymentStatusUseCase.kt
  core/network/src/main/java/team/retum/network/api/ApplicationApi.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSource.kt
  core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSourceImpl.kt
  core/network/src/main/java/team/retum/network/di/RequestUrls.kt
  core/network/src/main/java/team/retum/network/model/response/application/FetchEmploymentStatusResponse.kt
  feature/employment/.gitignore
  feature/employment/build.gradle.kts
  feature/employment/src/main/java/team/retum/employment/model/CompanyItem.kt
  feature/employment/src/main/java/team/retum/employment/navigation/EmploymentDetailNavigation.kt
  feature/employment/src/main/java/team/retum/employment/navigation/EmploymentNavigation.kt
  feature/employment/src/main/java/team/retum/employment/ui/EmploymentDetailScreen.kt
  feature/employment/src/main/java/team/retum/employment/ui/EmploymentScreen.kt
  feature/employment/src/main/java/team/retum/employment/viewmodel/EmploymentDetailViewModel.kt
  feature/employment/src/main/java/team/retum/employment/viewmodel/EmploymentViewModel.kt
  feature/employment/src/main/res/values/strings.xml
  feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
  feature/home/src/main/res/values/strings.xml
  feature/notification/src/main/java/team/retum/notification/navigation/NotificationsNavigation.kt
  feature/notification/src/main/java/team/retum/notification/ui/NotificationsScreen.kt
  feature/notification/src/main/java/team/retum/notification/viewmodel/NotificationsViewModel.kt
  feature/notification/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  settings.gradle.kts
Labels: 배포

#461 Feature/460 각 반별 페이지 타이틀 수정
  feature/employment/src/main/java/team/retum/employment/ui/EmploymentDetailScreen.kt
  feature/employment/src/main/java/team/retum/employment/viewmodel/EmploymentDetailViewModel.kt
Labels: 리팩토링
